--- 
abstract: toolkit for building RDF servers
author: James Smith, C<< <jsmith@cpan.org> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RDF-Server
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::MOP: 0
  Data::UUID: 0
  DateTime: 0
  HTTP::Request: 0
  HTTP::Response: 0
  HTTP::Status: 0
  Iterator::Simple: 0.04
  JSON::Any: 0
  Log::Handler: 0
  Moose: 0
  MooseX::Daemonize: 0
  MooseX::Types: 0
  POE::Component::Server::HTTP: 0
  RDF::Core: 0
  Sub::Exporter: 0
  Sub::Name: 0
  XML::LibXML: 0
  XML::Simple: 0
tests: t/*.t t/*/*.t
version: 0.01
